language: python
python:
- '3.7'
dist: xenial
before_install:
- cd ./app
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  matrix:
  - provider: heroku
    api_key:
      secure: 
    app: prophetdata
  api_key:
    secure: J7CaEd5q5iVEcY8pzSfUJqJKhCohZGvQdCrH6REErnOeGoJR5RRDlhNPhBNpdnfw6bwx3j8QMHK32njGmsGleKqf8dujOMwN1hOIOAF0/2vHve5YOmjzOyEXEZSR39TdKfJMczGbsG/XilMC5hZJQIrOkEjO0fpySJ82JKw00TRCgbcAy8LpH3ZQ3aSzkGQwvo2835G85TC9M8KXeA2VwAZC2RCLdsv8qy+y6KsYH2lACBlFq0REOJy88IeVC4LelXftc0if95vWGVh1P2fPtXHr03AdrVi8mxua1+6a4yQTNVAqvE7QkK/oGg6J/dRXaxMuqriNjNRDxNu8+8ZYXSW8fTG4YPXKNZR96LjHhcg0CDwHZxfxmt7SPpDjPJycb1gHsLW5TiJ2DdOwBfIlxYJffmUOquAlAXTj934y2P6FF16MN7ikhuXbVgFvyVqNk8G5uizRYvlSft36IoXm6thupbqNLlGzzMwgzwRGe0P3ByA4tAci32MbP51Vjdatsk+BOO3iIk1uAEmv/H4ZyTKuKZ32ywelv171z9gffVZWamFT/VCG3eL66Bhci91QQzssApTItCC7rLjp9Z7qB5Kzc0dIGHheYTNBGxYlh8W7OlfrtYKHmAhMrPbNa+CY+OJlWm0Fgh/s8DbiD1w/qEkkTVYnkAzQ8G5KlSwWY0s=
notifications:
  email:
  - leonardonhesi@gmail.com
