language: python
python:
- '3.7'
dist: xenial
before_install:
- cd ./app
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  matrix:
  - provider: heroku
    api_key:
      secure: 
    app: prophetdata
  api_key:
    secure: ViOkJ3eUd8wUlnjs1hb+/MMPi3XYdJIYhdWzWVPbDfB0A9q3bFMlBR9/xkBpxCU6zc7WOeZZpuNQMJDThF/ceNfzsrAgCzIAYHZpFu/ep/2WjY5RFEUCzbWrbO0074x/1XvNRTsoo1hJkKQjjXbQ2CsN9FTMElWiJu7wYEy3ImC8NtypoOil5Nst+6MVXm3VeLj3na5IXxci9doxQeNt2Kf+4LuE2rjXO+V962YxmPVM37EAqeXAF3r0nUvtgeJsVOp6SVgRT6f6OmYEXlU+6PL5Q0Iyzm7LbxKXEiJkL6LCTvRqtAZCH3ZkhUhlSlPSW99UAr5O53mEJbVqDSzRcs2Kk7KmA+0OW2zP1h12JQ50a47aTpBDD4bieW6qHyQMK90itOBJPHw5vE/URGixj1qLbhqrrDmxo4KMi/CltGheZHk2xhVFmv2lR+GCSsMFzGEqGV0QG9wnSbw2GUo/CgpyYeQ6svQMQDrISb7B5l48HmsXjyVu6miSjaFJFe+LfILXFUF6PgFOAXDJXoaeEWcP/JomQASBTZR+Cs0CGOualq002ekn1AcV7E+SImjQlQe0JK93sNi0US0njvFbqIt1sEswxoSo/YhMhYiHP0vmfaa5DgamIUxq5URCacwYtaF+aAB1L4kCkodHlImVUGlM+aQ+md6a2xT+MUs6S4M=
notifications:
  email:
  - leonardonhesi@gmail.com
