language: python
python:
- '3.7'
dist: xenial
before_install:
- cd ./app
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  matrix:
  - provider: heroku
    api_key:
      secure: 
    app: prophetdata
  api_key:
    secure: hOIa8oXl7tC/WW4yp7c2Ig0BGSCGw76XxFyWMmu6nBio8wq+OWaS78uWDHWod+lDVKoUb3AnOGLtargkjnDDW8wjlF1HgLvgJH6Y3z82vtNUwARWEyAdTZLbycxsRJDynnC3y0JvGP7dtqPlLH+fSoJUs5HefEMXOOydqWAUJDaJXRooZG/sFpfh56HO4l7C+q38x9Wv34y12zjJ0mLcl0TLAaDrdht8Nh5PjJjRm6RfQYj3vtXSzrQDvsbK9Ry265a9Td7IFckt/NoaquYNLzcaFExHCIb806LX705SfC0ZSW+7cV9b6R2mfV9drK+ojldTu/FNOc2CH/7asFmxA9zN2w4glv1Or332g08JviJeIaO2OGMEz/tjTRk4054S/KWFlnhACMllQfuwc4VBPa0wPvSZwLd07ll/s+sGsQvpmf9itbk1kCmGWMS+CTDcoNYflTEBkdaSqyYM9R9DFDvwm88Iua6/GR+XhEon/ybU2NnlvlP0jeg8dMOJlOzXN7noTYBDANa40/ekvriOEG0/Gmh0+BWsyQARLxpB5zp99Khzb+/AGzK6WumgzYdp2L1tq0EWrpFezWPqLhFWBsjeR7ZuJuWXMQidZ3Rx7HDFaEqeB/5QEIWHENfb2vio4lX/VHuTgnCWoExz6su6L+esOcJQglwfQKPlKCKcW4U=
notifications:
  email:
  - leonardonhesi@gmail.com
