language: python
python:
- '3.7'
dist: xenial
before_install:
- cd ./app
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  api_key: 
    secure: BurgkzFDzPmNwgf2gBzh8jYkDTlOdERzwNn3CnXe+aQtw93UVWvXhnX/Fh7s3nJm5GtsgQD9Ta00q5SMOdlGOgGEMTp/IPZAA5TtTgXtKpwwvAYKINklBzwBJudEeBjvezv/+Li2OSZgxhHkkqq+wd3G6Xu8dJbYhkoDdEJT8fbUdCg+pAfnbY36om9PNM9K2XPSZQifKfkZcXA+DnVKUXlmaJjpVyP6bC9JoGHZ2pWMoHUE4BbufT51NN5uoGixJzS+L8EUJRJU5CTdXXtdZ2xBwQF5c/YsFLOQhP6bM61i+bDnkGjh1TT3Qw60584SAIvizj0AzOKCgtvV2hQU1bc3Ox/XFrHDwMpqk2pQzQtRQk0Fu17DT1WUmhoqwbzO8nFs9DyYlthke6ZgdwpppktjgYpd097WbTmzm6n5QFVRSWWmIzMejAPjJXdRtUVjVu7ouZbCQwLW2ABVR8x/CHMokrVyPtcLtIOe+SZUmGLpXR77hPudDWvfmXPzNBs7RpmgnXt8PFr3hYwxRqfvJYV7jhhwsHKVEmDItq57dPPjVX/0BISYCZ0obvihEC/1eE9qYRKA+qKHsLvRRagg1gV8HygASQAgqGS/nucOAAs9ILbjT1n8TusBZ/i2kmlv4qhUwNzQ1+WD4TEc/ibgFlVwzUHLjKWQXuMVlCPI7LE=
  app: prophetMoedas
  on:
    repo: leonardonhesi/prophetMoedas
  skip_cleanup: 'true'
notifications:
  email:
  - leonardonhesi@gmail.com
