language: python
python:
- '3.7'
dist: xenial
before_install:
- cd ./app
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  matrix:
  - provider: heroku
    api_key:
     secure: Oq7u8yMEQ/cWQyLzqUzTphDWj1fENmG9vDKh+PFRS/VWvBhw2lFmytR9tDq22UxIbL0LKfzeNQABTPqkvhCuRo2Wp0f+E97tzSxG4q/iVTtoO3hL0pthFdI3AcJT4nCA7NsgxaeKSqBZyqZB+g6VM+HZZ4yJp+JsPgTFAoMwR2Ru902UEe+Nkzyu094KjeOSyou8wCiBtmj2Acjb/lLsCKjhuQz86AISx1xrdSdmPP6Z1n9KhGHnlidmeWyDNZNXQG64ePlPQ5wTd50I8lQssFADeA7hiwV3KbMMeAYRIbu/uRMZrN7+6hXlAoC8R3c51D3roHWKaE7hVJYeFmVxGpJJsrC4hNOlz8lE8FQKfY6EbozKzpF5yN6WGNEbGC7yl4jxb/7i5rvL8OLeQad3cR5ty2lRbQVlDxYV8jjN2jocyUnWJqtnlsQ0E4E52AMKGJ47Cqp0zWNOZY1BKy8ZV0hR57HpdmF31gWY4RtomXx4/H5Q/Hr85RDmb1GlvM7XPXqiuebY9UY7g9KWlPb9xfyGxF1d4RCTa/AC75+1Dokyt9zGG3CEUIVLpAHtWwtVOLeUDfDASzyDXTKLmhiGhZAtStermR1tZduqfp8OXnIK/QCBB6aYU//zip95hEn7YJ3ZA3q5hKBPC3OkLuMuZDF6J+7iygqybMF1zMQ2M8I=
    app: prophetdata