language: python
python:
- '3.7'
dist: xenial
before_install:
- cd ./app
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  matrix:
  - provider: heroku
    api_key:
      secure: 
    app: prophetdata
  api_key:
    secure: J0K89n12hr2Nt5L0VQKkBcfHZ/1pfqB2HlI+tnaNPISwpHZN+8STuv752hRvPkqURw/+aS1BI5RZ7Qx9EKMyAvhz8pumvA4OfbsbJCdxZI2cwF/KlY6QcUumszcW8oqPOC7PrBDe/Hl3+yLXsYJeBSzyEtIQnPGWOXXsrL017QmcxuKbMq6ZDrPP93FcWPKlyMKLKx/VRzljL9T+pgqd6btFP+GP0xwVinftODl1D5bkVxMKCEe3h9TwP2PoUrXHSE46u1ty+TSA75hPqCdCOTyUS6TNeXdwYZWIUOVB/b3CnGpGqTb11IlBQmjNd3mHOH/L2w2j5CAXjiAxx3OQHsNBEotwRWSbVWilSpeWZeUDtx1lg/N/F0AhiHs5N9Wr75BRf0lMvzogQPOQ+PzXUTO8Qit9G99xZMlRAAD0zxtjP6w4fvU0ZzBgiyxDyxa4ETmh1tSuzDgKuOBNBIY+PcMfw1SlJVzRuKYQ5vlveWh7i4J1MXRWmi5DnUmmUReAkoR1BrIJWVr2r99qMI0zhGv/YSHopwMSakofrwh7vNzj25QIsF8+v+g2rEMwL6ewHpSQXsTnjR0QtbM/EMuDmJKDFNRTFZRNKx5e7UTZ8mbPnjqHnNkRrTzhM1CKLmzxi/M6urP7ZpHSIhk8zZokRRJZrah44rLIYsmU3OIvN74=
notifications:
  email:
  - leonardonhesi@gmail.com
