language: python
python:
- '3.7'
dist: xenial
before_install:
- cd ./app
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
- provider: heroku
  secure: "H+pjySTWcVJqZyeyMKzaj4gMRC+uRybhWFBz+U0Gm+TqiSHNmxBuyzzBHp6+LPqVbs2vF3d2jGgYWhvztNPDDahX/SGe9ndhhy+f51eCSzccmT0cbrMG3J+tSwefXSdoQ7ZblyecP+tcyHDFJtuYIn6abX4Xzm4Thq0nnB0/eo6WjnMX36OyO7eR4z8yX2C9iOlI/eNV5VEYGSSKlm4TaOhf4QE0DueRZIa5Sfb09tyXuYOEKLyiNJzZtyxHV8iEOq698vPN56GQa8HCugCoyk/vlTElKG2BB/H8lXT0p8EP0MXg1X5sdDlY8hyQMpR3hR9rhIu58xtZGv22awX4Eb+7D3qqsRgO/8OZuF0JteGrXBEkASEjHwRjKDnOGi4zlOF9diVXJT87hJYibDvk2vio7zfkLVtRwDAnM1hF34pwz5d4dADvScSU8haJpCyzbv73zORi7NSonsnaQMPuORJRQefb8LQhVA4G40UDh0JxcMLyeH1PReZm4nVfIBe4o4w+2KmyiBOUKMQJUE/ytpjFVPtba8WvTggkohIvwokKaSOqR6IBLIYdfE0hqGhiBfj/XptNiZxIaKlr0R8kBJqATrLb4h++w1cLNbxP6/5+02696ZzoKWsSG5vTYMFW7KWnOaSC426W6G+oWJftDZazad3lSdwbKQNQzF2v2bk="
  app: prophetdata
notifications:
  email:
  - leonardonhesi@gmail.com